build:
  maxIssues: 0
  weights:
    complexity: 2
    comments: 2
    style: 1

config:
  validation: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 20
  LongMethod:
    active: true
    threshold: 120

style:
  active: true
  ForbiddenComment:
    active: true
    comments:
      - value: 'TODO:'
      - value: 'FIXME:'
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
